### ISSUE TITLE
Horizontal point labels too close

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/ShowCoordinatesOfSelectedNodes#1]
![screen shot 2015-10-11 at 9 33 42 am](https://cloud.githubusercontent.com/assets/1271897/10415769/cfeef238-6ffb-11e5-8bea-901bf7e8342c.png)

**Comment by mekkablue** [comment]
You will have to zoom in. There is not much I can do, except move it to another place, where the same problem will reoccur.
