### ISSUE TITLE
Coordinates difficult to read

### ISSUE THREAD

**Issue by NicholasSloan** [mekkablue/ShowCoordinatesOfSelectedNodes#3]
I find the bright green (and pale brown) tiny coordinates very difficult to read on a high res screen. ideally I'd like a choice of size and colour, but failing that, please could we have a significant increase in size and darker colours?

Many thanks.

**Comment by mekkablue** [comment]
I just had a look at it on a Retina screen, and the size appears bigger than the numbers you get from the built-in Measurement tool. If you want to change that, you would have to fork the repo and change the font size value in line 166 of `ShowCoordinatesOfSelectedNodes.py`.

I am making the green darker, the brown seems fine for me too. If you want to change the color in your fork, take a look at line numbers 141 and 159. And to see what colors are available, you can use one of these key words:
https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSColor_Class/index.html#//apple_ref/doc/uid/20000353-SW4

… or the RGBA method in line 159.

**Comment by NicholasSloan** [comment]
Many thanks Rainer.

Yes, I agree that the font size is at least not smaller than the grey info panel, but a) I find that too small as well, and b) the green is more difficult to read. Thanks very much for tips on tweaking it.

Nick

**Comment by NicholasSloan** [comment]
Thanks very much for this Rainer.
Node number has reappeared, and I’m very happy with being able to customise the size.
The only issue, and I’ll post it as an issue on GitHub, is that on horizontal nodes, unless the viewing scale is tightly zoomed in, the numbers clash. I am sending a screenshot to make things clearer in case I can’t upload it there.

Also, I was a bit puzzled about the colour definitions: named colour in line 141 is straightforward, but do I also need to define the node colour in line 166?  And did you mean 161 for 159?. It all works fine anyway, so I shouldn’t be bothering you with it. It’s a great plug-in, and makes a huge difference to the usefulness of Glyphs for me, so thanks very much.

All the best,
Nick
