### ISSUE TITLE
Clashing numbers

### ISSUE THREAD

**Issue by NicholasSloan** [mekkablue/ShowCoordinatesOfSelectedNodes#4]
Sorry Rainer, one more thing: with nodes on vertical paths, the coordinates space themselves nicely, but unless the view scale is zoomed in tight, the numbers of horizontal nodes tend to clash with one another, making them difficult to read. Not a fatal flaw (you can always zoom in) but is this tweakable?
Thanks
![number clash-2](https://cloud.githubusercontent.com/assets/20109637/16313670/310c82de-3972-11e6-9bee-18950f0d64a9.png)

**Comment by mekkablue** [comment]
Whichever solution you pick, the numbers will collide in one setting or another. For checking on small paths like small segments, you will always have to zoom in. What you could do is reduce the content of what is displayed. I’ll upload a version that gets rid of the .0 decimal and I took out the space after the at sign. New version coming up soon.

**Comment by NicholasSloan** [comment]
Fair enough Rainer.
Many thanks
Nick

PS I apologise for my country's vote to leave the EU yesterday. 48% of us are very unhappy about this, especially since the campaign was largely based on lies and xenophobia.
